"""initial schema

Revision ID: 47f3b5173084
Revises: 
Create Date: 2026-03-13 12:01:26.721172
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f3b5173084'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('record_type', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registry_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.Enum('INCOMING', 'OUTGOING', name='recordtype'), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'year', 'record_type', name='uq_counter_scope')
    )
    op.create_table('mailboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('imap_username', sa.String(length=255), nullable=False),
    sa.Column('imap_password_encrypted', sa.Text(), nullable=False),
    sa.Column('imap_use_ssl', sa.Boolean(), nullable=False),
    sa.Column('inbox_folder', sa.String(length=128), nullable=False),
    sa.Column('sent_folder', sa.String(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('prefix_code', sa.String(length=16), nullable=False),
    sa.Column('last_inbox_uid', sa.Integer(), nullable=True),
    sa.Column('last_sent_uid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('registry_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.Enum('INCOMING', 'OUTGOING', name='recordtype'), nullable=False),
    sa.Column('registry_number', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('mailbox_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('to_emails', sa.Text(), nullable=True),
    sa.Column('cc_emails', sa.Text(), nullable=True),
    sa.Column('bcc_emails', sa.Text(), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(length=512), nullable=True),
    sa.Column('thread_key', sa.String(length=512), nullable=True),
    sa.Column('mail_uid', sa.Integer(), nullable=True),
    sa.Column('mail_folder', sa.String(length=128), nullable=True),
    sa.Column('message_hash', sa.String(length=128), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('attachments_count', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('storage_url', sa.String(length=1024), nullable=True),
    sa.Column('linked_record_id', sa.Integer(), nullable=True),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['linked_record_id'], ['registry_records.id'], ),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registry_number')
    )
    op.create_index('ix_registry_records_from_email', 'registry_records', ['from_email'], unique=False)
    op.create_index('ix_registry_records_mailbox_id', 'registry_records', ['mailbox_id'], unique=False)
    op.create_index('ix_registry_records_message_id', 'registry_records', ['message_id'], unique=False)
    op.create_index('ix_registry_records_received_at', 'registry_records', ['received_at'], unique=False)
    op.create_index('ix_registry_records_record_type', 'registry_records', ['record_type'], unique=False)
    op.create_index('ix_registry_records_registry_number', 'registry_records', ['registry_number'], unique=False)
    op.create_index('ix_registry_records_responsible_user_id', 'registry_records', ['responsible_user_id'], unique=False)
    op.create_index('ix_registry_records_sent_at', 'registry_records', ['sent_at'], unique=False)
    op.create_index('ix_registry_records_status_id', 'registry_records', ['status_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('storage_url', sa.String(length=1024), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['registry_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_index('ix_registry_records_status_id', table_name='registry_records')
    op.drop_index('ix_registry_records_sent_at', table_name='registry_records')
    op.drop_index('ix_registry_records_responsible_user_id', table_name='registry_records')
    op.drop_index('ix_registry_records_registry_number', table_name='registry_records')
    op.drop_index('ix_registry_records_record_type', table_name='registry_records')
    op.drop_index('ix_registry_records_received_at', table_name='registry_records')
    op.drop_index('ix_registry_records_message_id', table_name='registry_records')
    op.drop_index('ix_registry_records_mailbox_id', table_name='registry_records')
    op.drop_index('ix_registry_records_from_email', table_name='registry_records')
    op.drop_table('registry_records')
    op.drop_table('mailboxes')
    op.drop_table('registry_counters')
    op.drop_table('domains')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('statuses')
    op.drop_table('companies')
    # ### end Alembic commands ###
